//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Antecedentes = new HashSet<Antecedentes>();
            this.Fotos = new HashSet<Fotos>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public string CI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string DescripcionFisica { get; set; }
        public string Email { get; set; }
        public string Nivel { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> ciudadId { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Antecedentes> Antecedentes { get; set; }
        public virtual ICollection<Fotos> Fotos { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
