//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.PermisosPorRoles = new HashSet<PermisosPorRoles>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<PermisosPorRoles> PermisosPorRoles { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
